package scanner_tokenizer;

public enum TokenType {
	EOF, IDENT, NUM8, NUM, SKIP, BOOL, IN, FALSE, FOR, POP, PRINT, PUSH, TOP, TRUE, VAR, PLUS, DIV, TIMES, ASSIGN, OPEN_PAR, CLOSED_PAR, STMT_SEP, EXP_SEP, START_BLOCK, END_BLOCK, OR, AND, EQ, LTH, NOT, MINUS, START_LIST, END_LIST, CONCAT, FIRST, PAIR, SECOND, LENGTH, IF, ELSE, WHILE
	}
